plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.1-rc.2.cjs

packageExtensions:
  "ts-node@9.1.1":
    dependencies:
      typescript: ">=2.7"
  "eslint-config-react-app@6.0.0":
    dependencies:
      babel-eslint: "^10.0.0"
  "fork-ts-checker-webpack-plugin@4.1.6":
    dependencies:
      typescript: ">=2.7"
      webpack: ">=4"